version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      root-python-dependencies:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: /src/olympus_copilot_sdk/01_sp
    schedule:
      interval: weekly
    groups:
      sharepoint-python-dependencies:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: /src/olympus_copilot_sdk/02_adb
    schedule:
      interval: weekly
    groups:
      databricks-python-dependencies:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
    open-pull-requests-limit: 5